In [4]:
import numpy as np

In [16]:
def CycleToChromosome(Nodes): 
    n = int(len(Nodes)/2)
    Chromosome = np.zeros(n)
    for j in range(n):
        if Nodes[2*j] < Nodes[2*j+1]:
            Chromosome[j] =  Nodes[2*j+1] /2
        else:
            Chromosome[j]  = -Nodes[2*j]/2
    return Chromosome

In [17]:
Nodes = '(1 2 4 3 6 5 7 8)'
Nodes = Nodes[1:len(Nodes)-1]
Nodes = np.array(Nodes.split(' ')).astype(int)    

In [18]:
Nodes

array([1, 2, 4, 3, 6, 5, 7, 8])

In [19]:
CycleToChromosome(Nodes)

array([ 1., -2., -3.,  4.])

In [29]:
file = open('dataset_369340_5.txt', 'r') 
for i, line in enumerate(file):
    line=line.rstrip('\n')
    line = line[1:len(line)-1]
    if(i==0):
        sequence = np.array(line.split(' ')).astype(int)    

In [30]:
sequence

array([  1,   2,   4,   3,   5,   6,   7,   8,   9,  10,  12,  11,  13,
        14,  16,  15,  18,  17,  19,  20,  22,  21,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  36,  35,  37,  38,  39,
        40,  41,  42,  44,  43,  45,  46,  47,  48,  50,  49,  52,  51,
        53,  54,  56,  55,  58,  57,  60,  59,  62,  61,  64,  63,  65,
        66,  67,  68,  69,  70,  71,  72,  74,  73,  76,  75,  77,  78,
        80,  79,  82,  81,  83,  84,  86,  85,  88,  87,  89,  90,  92,
        91,  94,  93,  96,  95,  98,  97,  99, 100, 101, 102, 104, 103,
       106, 105, 107, 108, 109, 110, 112, 111, 113, 114, 116, 115, 118,
       117, 119, 120, 122, 121, 124, 123, 125, 126, 128, 127, 130, 129,
       131, 132, 134, 133, 135, 136, 137, 138])

In [31]:
output = CycleToChromosome(sequence)

In [32]:
print('(',end='')
for out in output:
    print("%+d"%out,end = ' ')
print(')')

(+1 -2 +3 +4 +5 -6 +7 -8 -9 +10 -11 +12 +13 +14 +15 +16 +17 -18 +19 +20 +21 -22 +23 +24 -25 -26 +27 -28 -29 -30 -31 -32 +33 +34 +35 +36 -37 -38 +39 -40 -41 +42 -43 -44 +45 -46 -47 -48 -49 +50 +51 -52 -53 +54 +55 -56 +57 -58 -59 +60 -61 -62 +63 -64 -65 +66 -67 +68 +69 )
