In [75]:
import numpy as np

In [126]:
def GraphToGenome(GenomeGraph):
    P = []
    First = GenomeGraph[0][0]
    ChangeFirst = 0
    Chr = []
    for Nodes in GenomeGraph:
        Chr.append(Nodes[0])
        if(ChangeFirst==1):
            First = Nodes[0]
            ChangeFirst=0
            Chr = [Nodes[0],Nodes[1]]
            continue
        if(abs(Nodes[1]-First)==1):
            ChangeFirst = 1
            Chr.insert(0,Nodes[1])
        
            Chromosome = CycleToChromosome(Chr)
            
            P.append(Chromosome)
        else:
            Chr.append(Nodes[1])
            
    return P

In [127]:
def CycleToChromosome(Nodes): 
    n = int(len(Nodes)/2)
    Chromosome = np.zeros(n).astype(int)
    for j in range(n):
        if Nodes[2*j] < Nodes[2*j+1]:
            Chromosome[j] =  Nodes[2*j+1] /2
        else:
            Chromosome[j]  = -Nodes[2*j]/2
    return Chromosome

In [128]:
line = '(2, 4), (3, 6), (5, 1), (7, 9), (10, 12), (11, 8)'
line = line[1:-1]
line = line.split('), (')
Edge = []
for node in line:
    node1,node2 = node.split(', ')
    Edge.append((int(node1),int(node2)))
    

In [129]:
Edge[0][0]

2

In [130]:
P = GraphToGenome(Edge)

In [131]:
for Chr in P:
    print('(',end='')
    for i in range(len(Chr)-1):
        print("%+d"%Chr[i],end = ' ')
    print("%+d)"%Chr[-1],end='')

(+1 -2 -3)(-4 +5 -6)

In [136]:
Edge = []
file = open('dataset_369340_8.txt', 'r') 
for i, line in enumerate(file):
    line=line.rstrip('\n')
    if(i==0):
        line = line[1:-1]
        line = line.split('), (')
        Edge = []
        for node in line:
            node1,node2 = node.split(', ')
            Edge.append((int(node1),int(node2)))
    

In [137]:
P = GraphToGenome(Edge)

In [138]:
for Chr in P:
    print('(',end='')
    for i in range(len(Chr)-1):
        print("%+d"%Chr[i],end = ' ')
    print("%+d)"%Chr[-1],end='')

(-1 -2 -3 -4 +5 +6 +7 -8 +9 -10 +11 +12 -13 -14 +15 +16 +17 -18 -19 -20 +21)(+22 +23 -24 +25 +26 -27 -28 -29 -30 +31 +32 +33 -34 -35 -36 -37 +38 -39 +40 +41 +42 +43 -44 +45 +46)(+47 +48 +49 +50 +51 +52 +53 +54 -55 -56 +57 -58 -59 -60 +61 -62 +63 -64 +65 -66 -67 -68 -69 +70 -71 -72 -73 -74 +75 +76)(+77 -78 +79 +80 -81 -82 +83 -84 +85 +86 -87 -88 -89 +90 +91 -92 +93 +94 -95 -96 +97 -98 +99 +100 -101 -102 -103 -104 -105)(-106 -107 +108 -109 +110 +111 +112 +113 -114 -115 +116 -117 +118 +119 +120 +121 +122 +123 -124 +125 -126 -127 -128 -129)(+130 +131 -132 -133 -134 -135 +136 +137 -138 +139 +140 +141 -142 -143 -144 +145 +146 -147 +148 -149)(-150 +151 -152 -153 +154 +155 +156 +157 -158 +159 +160 +161 -162 +163 +164 -165 -166 +167 -168 +169 +170 +171)

In [135]:
P

[array([ -1,   2,  -3,   4,  -5,  -6,   7,  -8,   9,  10,  11,  12,  13,
         14, -15,  16, -17, -18, -19,  20]),
 array([ 21, -22, -23,  24, -25,  26,  27, -28,  29,  30,  31,  32,  33,
        -34,  35,  36, -37,  38,  39, -40,  41,  42,  43,  44,  45, -46,
        -47, -48,  49, -50]),
 array([ 51,  52, -53, -54, -55,  56,  57, -58, -59,  60, -61, -62, -63,
         64,  65, -66, -67,  68,  69,  70, -71,  72, -73,  74]),
 array([ -75,   76,   77,   78,   79,   80,   81,   82,  -83,   84,  -85,
         -86,   87,  -88,  -89,  -90,  -91,   92,   93,   94,  -95,   96,
         -97,  -98,   99,  100, -101,  102, -103]),
 array([ 104, -105, -106,  107, -108,  109,  110,  111, -112,  113, -114,
        -115, -116, -117,  118, -119,  120,  121,  122,  123, -124, -125]),
 array([ 126,  127, -128,  129,  130, -131, -132,  133,  134, -135, -136,
        -137,  138, -139,  140,  141, -142,  143,  144, -145,  146,  147,
         148, -149,  150,  151, -152,  153,  154]),
 array([ 155, -156